version: '2'
services:

  database:
    image: mysql:latest
    container_name: fwgram-database
    volumes:
      - ./database/mysql/conf.d:/etc/mysql/conf.d
      - ./database/mysql/data:/var/lib/mysql
      - ./database/mysql/log:/var/log/
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=0.0.0.0
      - MYSQL_DATABASE=fwgram
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - right=WRITE
